server:
  port: 9090

spark:
  appName: ddpig
  master: local[4]
  props:
    spark.serializer: org.apache.spark.serializer.KryoSerializer
    spark.kryo.registrator: org.datasyslab.geospark.serde.GeoSparkKryoRegistrator
    es.nodes: 192.168.101.22:9200
    es.nodes.wan.only: true
    es.http.timeout: 30s
    es.mapping.date.rich: false
